/**
 * Generated by scripts/generate-images.mjs — do not edit by hand.
 *
 * Run `npm run images` after adding a master to assets/source.
 */

/**
 * Inline 24px previews, one per photograph. They hold the frame on the first
 * paint so nothing reflows when the real file arrives, and cost no request.
 */
export const BLUR: Record<string, string> = {
  'team/karthik': 'data:image/webp;base64,UklGRswAAABXRUJQVlA4IMAAAADQBACdASoYAB4APt1kqE+opaOiKAqpEBuJZwCzgDTuGNKhVTnGhX0lNMeDKsxZgAD+ZtRXLrtsl6tpz5eoeK1LpKPJi5PQM5RNAKEQZlziVffvDz50eg/sFHnl3J+sgqsh0Jx9pwRWI92np58QlJ+/+AIbqFUFSLgvv8xCWBmcG8iBfY+WFd1ojUwx2Iti9RNJIY4OsvLYS5EnDWqnWPMLl9qdKJmfForwHAA0gvnt5T/ZtZiRnBna2LXkergAAAA=',
  'team/sanskrithi': 'data:image/webp;base64,UklGRhIBAABXRUJQVlA4IAYBAABQBgCdASoYAB4APt1cpUyopSOiMAgBEBuJZgC7BbRlGxr4g79rmLxOIQ51pnAwAvWLSn4uLTiPcMCeAAD+22pdKFf62bgYkW+w/3glqidM5i6rXtgD4DZxz3WZ2kSeXnlF5BO1yzKWqJAY0aVLKNmBkAQfD2G3MuSA/Nq1/wy9bSq0L2/4Pn+JENH3SrLjfljkCi0a5t8PQWYfaj/LyBUlDE4PuQBuEgbGhDyDTadYlmwrexAw4mXchsZG9hb5Dp7An9gElbHlQxR0+rAgeXOd2U2oqIuKIxF2AkRmNwJBLZF9XIq185zJP+2rCXUc82V1b6IyJfXiYB2QlauX+D87lClHhpAA',
  'team/mithilesh': 'data:image/webp;base64,UklGRg4BAABXRUJQVlA4IAIBAACQBgCdASoYAB4APt1kp02opiOiMBgIARAbiUAVx5zQfja1DIN34xyiI+mRn3gH3AQlXHfp0nIY2IVVF4o4AP65851G12HIfIc5+LHdu68NRKYkcm58EaxatPyBJOjhXqgOY1qiw1Ese3gLT5mqKsu2r/l2BJ1VWULOCAlRcE0wl1lwrSwJLYAkr94grgr855A24SP93Fra3AKW2mx8GoSPtInIc/N11vyAVSPm+tjSCHzvhQJC9SGYYeo8w3knXwuFjtlsDybmtIp/lyUjjyFcw8ktE/vit5qe06dp9yLoqVlrItRfmO/IALbjlieTx+VmiW7fPcSoycP17TT5JtZwAAA=',
  'team/poosan': 'data:image/webp;base64,UklGRioBAABXRUJQVlA4IB4BAACQBgCdASoYAB4APtVaokyoJSMiMAwBABqJZgC7IJPg0Bf7rKSs8sjgaE4TP6uM3xzRoFAbiATtk8qZi1u8AP5b2cET3kqNKOGRGf4z4kk5GsrOC2xw34pMCV0hb28e1+Mr/wyrlu35WIanxpxzjW4QByfMUnSflvASKoj4cbMDDIZSq8Xr4gGJ0Xf/ztcEk9lx5wFZIhzJAZaixPDWQgM3EtnMYZLYNrMhBp33Z3tHXGAV0hKz3JI3nOZ0BAj5cX6A6zkfwO9tDPtOpAiRsqTwCgs7c21mjhzR3KV3pzOa8MAADEnCS89/6EeHdz1F/PhTpuym0xTPM7Z5GOsi9LPT+1LqUgSlmkZqLsWedbLg96qCyqGfY1X4ytvMAAAA',
  'team/thakarshi': 'data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAABQBgCdASoYAB4APt1aqE6opKOiMBgIARAbiWwAtOwIHZVONpoMT+bNpmH7jgEfrz1YihWntHhwcR9HAAD+lSVtkfj2t2nZwOilds/myOP32w0CFVwR4WqxJJvxnd5aTJ9sFOzZ8DITgXJS5OGOeX6GOHFy2wdztd/ibECeXN4ZVfiSNaBs3THCXdBp8ZxySQBlppPHWyW1alCeDEfZbmAKZopRzGaVmGrJjc5ffKIQqaCySAvl+3ohl0s5GuES5IBrbTZVVQaB1mC7aFWDHetotaIZVbJX9czN6CEhdoXkV8o7Id+emOxrGTgMtdvJlBAjmiU2CusWqHECt+sQl8T5A1q1hPp6cjesXeSzFSNiZx6w1DkWoHz2FcYnag/snHM5ZUCD2mhBAAAA',
  'team/vibhu': 'data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAAAwBgCdASoYAB4APt1cqU0opSQiKA1REBuJaACdMzAOAhGtZ6MLz7EhMCeVvGV0z9bnWAJka87qoGgAAP70MsqN/Cnb7zdep7AavvP95dSYhtnIKspGjKeOkJEB/5t9oo0USXTkPiycvXJapAKrVdrWZveN35Q2IY6WnZEJVv2cl6ZL4x26Lyb9WQeBvEBiWmHUsF3rinyiPuITuj3Y4K4axBgeN9qQsfISf8YHwQlyxOfagQG62ltp4gDsKYsntdWS8qK26f6GwL3RKGGYKmN9C8rV3mERShw0bl6D3rPSWG08VEUQmzLSvPqei7GFRGCqdW6YAjG23L4I4XVYY9qttULTMeUlSSSa/tTLK1g9oCXPdwyQXsoi8WZI5gcG4zq9AK2mkTQeBYAA',
  'team/alen': 'data:image/webp;base64,UklGRhwBAABXRUJQVlA4IBABAACQBQCdASoYAB4APt1eqE0opSQiKA1REBuJbACdMoMulH5TNfWT4c/e6A00Eg2j2SCbIt3aYADKZg44K/S6QUOiWIxjrvGEQla45vqgNNBwMCF4R5cL0J/fhPqH43N2FuTugN/Nj9PU86YPh9wTmmC0f+CTYJoq4bc47VPbtzRJVdPZJ80pWX0lH2f/jBEsNpyzSItZFUviGSIwHd6FUzQlbBccoE538CTb9RzUNtnxboHy0wM7m7T1iSEyaR14wuCtoPNH70wEIkKgMyUTD6AHt5mQdLgGi67loZcpwkgu5JNdPSKRR4rZXBwLuAmc03WulXo4hOwJl79+nZkuD2AmQ4TBFzSa6427Qe6hazAAAA==',
};

/** Which widths actually exist on disk, so a srcSet never points at a 404. */
export const WIDTHS: Record<string, number[]> = {
  'team/karthik': [480, 768],
  'team/sanskrithi': [480, 768],
  'team/mithilesh': [480, 768],
  'team/poosan': [480, 768],
  'team/thakarshi': [480],
  'team/vibhu': [480, 768],
  'team/alen': [480],
};

/**
 * The base name for a generated file, or null if this URL is not one of ours.
 *
 * "/image/partners/nib-and-nosh-1024.webp" → "partners/nib-and-nosh"
 */
export function generatedNameFor(url: string): string | null {
  const match = /^\/image\/(.+?)-\d+\.webp$/.exec(url);
  if (match && WIDTHS[match[1]]) return match[1];

  // Also accept the bare name, so a caller can address the photograph without
  // committing to one of its widths.
  const bare = url.replace(/^\/image\//, '').replace(/\.webp$/, '');
  return WIDTHS[bare] ? bare : null;
}
